#!/usr/bin/env python3
"""
Generate fully passing simulated SDK smoke evidence (including placeholder artifacts).

This is intended for container/CI environments where real Acrobat host execution
is unavailable, while still exercising the same release-gate schema.
"""

from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path


MATRIX = (
    ("Windows 11 23H2", "x64"),
    ("macOS 14 Sonoma", "arm64"),
    ("macOS 14 Sonoma", "x64 (Rosetta/Intel)"),
)


def _write_placeholder(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--out", required=True, help="Output evidence JSON path.")
    parser.add_argument(
        "--artifact-root",
        required=True,
        help="Root directory for per-row simulated artifact bundles.",
    )
    args = parser.parse_args()

    out_path = Path(args.out)
    root = Path(args.artifact_root)
    now = datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")

    rows: list[dict] = []
    for os_name, cpu in MATRIX:
        safe = f"{os_name}-{cpu}".replace(" ", "_").replace("/", "_").replace("(", "").replace(")", "")
        bundle = root / safe
        proof = bundle / "proof.pdf"
        imposed = bundle / "imposed-output.pdf"
        preflight = bundle / "preflight.json"
        sdk_ops = bundle / "sdk-ops.json"
        control = bundle / "control-surface.json"

        _write_placeholder(proof, "%PDF-1.4\n% simulated proof\n")
        _write_placeholder(imposed, "%PDF-1.4\n% simulated imposed output\n")
        _write_placeholder(preflight, json.dumps({"status": "ok", "errorCount": 0}) + "\n")
        _write_placeholder(
            sdk_ops,
            json.dumps({"kind": "acrobat-sdk-placement-ops", "operations": []}, indent=2) + "\n",
        )
        _write_placeholder(
            control,
            json.dumps({"kind": "acrobat-imposition-control-surface", "version": 1}, indent=2) + "\n",
        )

        rows.append(
            {
                "os": os_name,
                "cpu": cpu,
                "execution_mode": "simulated-runtime",
                "acrobat_version": "simulated-acrobat",
                "sdk_version": "simulated-sdk",
                "run_timestamp_utc": now,
                "plugin_load": "pass",
                "menu_actions": "pass",
                "preset_validate": "pass",
                "preset_preview": "pass",
                "preset_run_bundle": "pass",
                "runtime_quality_gate": "pass",
                "imposed_output_open": "pass",
                "panel_quick_actions": "pass",
                "bundle_path": str(bundle),
                "proof_pdf_path": str(proof),
                "imposed_output_path": str(imposed),
                "preflight_json_path": str(preflight),
                "sdk_ops_path": str(sdk_ops),
                "control_surface_path": str(control),
                "notes": "generated by simulated-runtime tool",
            }
        )

    payload = {"rows": rows}
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")
    print(f"Wrote simulated evidence: {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())

